"""Metrics routes — the platform-wide telemetry rollup.

Six endpoints back one screen: the six KPI cards, the six trend charts, the
per-model table with its usage donut, the runs-by-platform donut, the Export
button -- and ``/overview``, which answers the cards and both breakdowns from a
single measurement. Every route is a read; the screen has no verbs.

Handlers parse, delegate and shape. Window arithmetic, workspace scoping and
every engine call live in ``services.metrics``.
"""

from __future__ import annotations

import datetime as dt
from typing import Annotated, Any

from fastapi import APIRouter, Depends, Query
from fastapi.responses import StreamingResponse

from ...schemas.metrics import (
    MetricInterval,
    MetricsDailyRow,
    MetricsExportDataset,
    MetricsOverview,
    MetricsSeriesResponse,
    MetricsSummary,
    MetricWindow,
    ModelUsageRow,
    PlatformUsageRow,
    SeriesMetric,
)
from ...services import metrics as service
from ..common import ListParams, Page, list_params, to_csv
from ..deps import CurrentPrincipal, Db

#: Narrow every measurement to specific agents. Repeat the parameter to compare
#: a few; omit it for the whole workspace. Filtering happens when the telemetry
#: namespaces are resolved, so an agent the workspace does not own is simply not
#: asked for rather than filtered out afterwards.
AgentFilter = Annotated[
    list[str] | None,
    Query(alias="agent_id", description="Repeat to include several agents"),
]

router = APIRouter(prefix="/metrics", tags=["Metrics"])

WindowQuery = Annotated[
    MetricWindow, Query(description="Measurement window: 24h, 7d, 30d or 90d")
]
IntervalQuery = Annotated[
    MetricInterval | None,
    Query(description="Bucket width; defaults to the natural one for the window"),
]

#: Sort keys the model and platform tables accept, and the columns searched.
MODEL_SORTABLE = (
    "model",
    "agent_count",
    "runs",
    "tokens",
    "cost_usd",
    "avg_latency_seconds",
    "success_rate_percent",
    "tokens_share_percent",
    "cost_share_percent",
)
PLATFORM_SORTABLE = ("platform", "agent_count", "runs", "runs_share_percent", "tokens", "cost_usd")


def _attachment(name: str) -> dict[str, str]:
    stamp = dt.datetime.now(dt.UTC).strftime("%Y%m%d")
    return {"Content-Disposition": f'attachment; filename="{name}-{stamp}.csv"'}


@router.get("/summary", response_model=MetricsSummary, summary="Platform KPI summary")
async def get_summary(
    principal: CurrentPrincipal,
    session: Db,
    window: WindowQuery = MetricWindow.LAST_30D,
    agent_id: AgentFilter = None,
) -> MetricsSummary:
    """The six KPI cards with their period-over-period deltas.

    Each card is measured twice — once over the window, once over the window
    immediately before it — so the delta compares equal spans of time. A measure
    the telemetry store does not report comes back null rather than zero.
    """
    return await service.summarise(session, principal, window, agent_id)


@router.get(
    "/overview",
    response_model=MetricsOverview,
    summary="KPI summary and both breakdowns, measured once",
)
async def get_overview(
    principal: CurrentPrincipal,
    session: Db,
    window: WindowQuery = MetricWindow.LAST_30D,
    agent_id: AgentFilter = None,
) -> MetricsOverview:
    """Everything on the screen that is not a chart, from one measurement.

    `summary` is exactly what `/metrics/summary` answers; `models` and
    `platforms` are every row of `/metrics/models` and `/metrics/platforms` in
    their default order (heaviest first). The breakdowns are a handful of rows,
    so they arrive whole and the console sorts, searches and pages them itself:
    a column-header click then costs the telemetry store nothing.
    """
    return await service.overview(session, principal, window, agent_id)


@router.get(
    "/series",
    response_model=MetricsSeriesResponse,
    summary="Time series for the trend charts",
)
async def get_series(
    principal: CurrentPrincipal,
    session: Db,
    window: WindowQuery = MetricWindow.LAST_30D,
    interval: IntervalQuery = None,
    metric: Annotated[
        list[SeriesMetric] | None,
        Query(description="Repeat to overlay lines on one chart"),
    ] = None,
    agent_id: AgentFilter = None,
) -> MetricsSeriesResponse:
    """One or more lines on a shared bucket grid.

    Ask for `metric=latency_p50&metric=latency_p90` to get the two-line latency
    chart, or `metric=violations&metric=escalations` for the governance chart;
    omit `metric` and all eight lines come back. Buckets are generated by this
    API, so engine-sourced and governance-sourced lines share an x axis.
    """
    wanted = list(metric) if metric else list(SeriesMetric)
    return await service.series(
        session, principal, window=window, interval=interval, metrics=wanted, agent_ids=agent_id
    )


@router.get(
    "/models",
    response_model=Page[ModelUsageRow],
    summary="Per-model usage breakdown",
)
async def list_models(
    principal: CurrentPrincipal,
    session: Db,
    params: Annotated[ListParams, Depends(list_params)],
    window: WindowQuery = MetricWindow.LAST_30D,
    agent_id: AgentFilter = None,
) -> Page[ModelUsageRow]:
    """Runs, tokens, cost, latency and success rate for every model in use.

    Rows are ordered heaviest-token-consumer first and carry their share of the
    workspace total, which is what the donut beside the table draws. Sort with
    `sort=` on any numeric column; search matches the model name.
    """
    rows = await service.model_rows(session, principal, window, agent_id)
    page, total = service.paginate_rows(
        rows,
        params,
        sortable=MODEL_SORTABLE,
        default_key="tokens",
        search_keys=("model",),
    )
    return Page.build(service.to_model_rows(page), total, params.page, params.page_size)


@router.get(
    "/platforms",
    response_model=Page[PlatformUsageRow],
    summary="Runs by platform",
)
async def list_platforms(
    principal: CurrentPrincipal,
    session: Db,
    params: Annotated[ListParams, Depends(list_params)],
    window: WindowQuery = MetricWindow.LAST_30D,
    agent_id: AgentFilter = None,
) -> Page[PlatformUsageRow]:
    """Run volume grouped by the platform each agent runs on.

    Backs the Runs by Platform donut: every row carries its share of total runs
    and the colour key the legend uses.
    """
    rows = await service.platform_rows(session, principal, window, agent_id)
    page, total = service.paginate_rows(
        rows,
        params,
        sortable=PLATFORM_SORTABLE,
        default_key="runs",
        search_keys=("platform",),
    )
    return Page.build(service.to_platform_rows(page), total, params.page, params.page_size)


@router.get(
    "/export",
    summary="Export metrics as CSV",
    response_class=StreamingResponse,
)
async def export_metrics(
    principal: CurrentPrincipal,
    session: Db,
    params: Annotated[ListParams, Depends(list_params)],
    window: WindowQuery = MetricWindow.LAST_30D,
    interval: IntervalQuery = None,
    dataset: Annotated[
        MetricsExportDataset, Query(description="Which table to export")
    ] = MetricsExportDataset.SERIES,
    agent_id: AgentFilter = None,
) -> StreamingResponse:
    """Stream one of the screen's three tables as CSV.

    `dataset=series` (the default) exports one row per bucket with the charted
    measures; `models` and `platforms` export the two breakdown tables over the
    same filters — including `q` and `sort` — that the on-screen table is using.
    """
    if dataset is MetricsExportDataset.MODELS:
        rows = service.filter_rows(
            await service.model_rows(session, principal, window, agent_id),
            params,
            sortable=MODEL_SORTABLE,
            default_key="tokens",
            search_keys=("model",),
        )
        return StreamingResponse(
            iter([to_csv(rows, service.MODEL_EXPORT_COLUMNS)]),
            media_type="text/csv; charset=utf-8",
            headers=_attachment("platform-metrics-models"),
        )

    if dataset is MetricsExportDataset.PLATFORMS:
        rows = service.filter_rows(
            await service.platform_rows(session, principal, window, agent_id),
            params,
            sortable=PLATFORM_SORTABLE,
            default_key="runs",
            search_keys=("platform",),
        )
        return StreamingResponse(
            iter([to_csv(rows, service.PLATFORM_EXPORT_COLUMNS)]),
            media_type="text/csv; charset=utf-8",
            headers=_attachment("platform-metrics-platforms"),
        )

    daily: list[dict[str, Any]] = await service.daily_rows(
        session, principal, window=window, interval=interval, agent_ids=agent_id
    )
    # Validate on the way out so the CSV and the JSON API can never disagree
    # about what a column is called.
    payload = [MetricsDailyRow.model_validate(row).model_dump(mode="json") for row in daily]
    return StreamingResponse(
        iter([to_csv(payload, service.DAILY_EXPORT_COLUMNS)]),
        media_type="text/csv; charset=utf-8",
        headers=_attachment("platform-metrics"),
    )
